### ISSUE TITLE
Error when running 'sudo tp-auto-kbbl'

### ISSUE THREAD

**Issue by Archadox** [saibotd/tp-auto-kbbl#4]
When the command `sudo tp-auto-kbbl` is ran, the following error is displayed

Input device ID: bus 0x19 vendor 0x0 product 0x1
Evdev version: 10001
Input device name: "Power Button"
Phys location: LNXPWRBN/button/input0
Setting brightness to 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: The name org.freedesktop.UPower was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by saibotd** [comment]
Seems to be an D-Bus issue… do you have dbus installed? Also you gotta find out which device is your keyboard. Could you post the output of `hwinfo --short`?

**Comment by Archadox** [comment]
> Seems to be an D-Bus issue… do you have dbus installed? Also you gotta find out which device is your keyboard. Could you post the output of `hwinfo --short`?

Thank you! I had the wrong version of Dbus installed, reinstalling it fixed the problem. Thank you for the great program!
